<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>HiggsTts.Net</AssemblyName>
    <RootNamespace>HiggsTts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HiggsTtsSharp\HiggsTtsSharp.csproj" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

</Project>
